# Generated by Django 3.2.9 on 2021-11-20 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actorcomment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='moviecomment',
            name='category',
        ),
    ]
